### ISSUE TITLE
gulp error

### ISSUE THREAD

**Issue by engtmk** [shahboura/currency-scraper#11]
We got this error when trying to run gulp 
currency-scraper/gulpfile.js:3
let gulp = require('gulp'),
^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (/usr/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/lib/node_modules/gulp/node_modules/liftoff/index.js:198:16)
    at module.exports (/usr/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/usr/lib/node_modules/gulp/node_modules/liftoff/index.js:190:9)

**Comment by shahboura** [comment]
@engtmk can you provide more details about the environment? 
Node version? OS?

**Comment by engtmk** [comment]
hyg
node v0.10.46, CentOS release 6.8 (Final)

**Comment by shahboura** [comment]
Ahaa, I guess the problem in your node version. Don't think the let feature is implemented by default. 
Wet can check ES6 feature matrix in:
http://node.green

More on the issue:
https://nodejs.org/en/docs/es6/
http://stackoverflow.com/questions/11283538/does-node-js-support-the-let-statement/11326647#11326647

Solution: update node to v4.3.2 or above
Let me know if this works out for you, I'll update the README file accordingly.

**Comment by engtmk** [comment]
thanx working now with node v6.9.1

**Comment by engtmk** [comment]
right now it is other issue Cannot GET /currencies

**Comment by shahboura** [comment]
You should prefix it with "api" since its Web API
Final url api/currencies
https://github.com/shahboura/currency-scraper/blob/develop/app.js#L15

In addition remember it's goes on intervals for historical data analysis, by default interval is 15 mimutes. This is also configurable. If you don't want the interval simply invoke the scraper method normally.

**Comment by shahboura** [comment]
Closed as node version support for let

**Comment by shahboura** [comment]
Updated README.md file for less confusion 1eac35369de1911db2d85e0b2e1ffe44fe396666
