### ISSUE TITLE
gulp error

### ISSUE THREAD

**Issue by hema-developer** [shahboura/currency-scraper#20]
`events.js:72
      listeners[i].call(self);
                  ^

TypeError: Cannot read property 'call' of undefined
    at emitNone (events.js:72:19)
    at SockJSConnection.emit (events.js:166:7)
    at cleanup (E:\xampp\htdocs\test\node_modules\shoe\index.js:25:20)
    at Session.stream._session.didTimeout (E:\xampp\htdocs\test\node_modules\shoe\index.js:14:13)
    at Session.timeout_cb [as _onTimeout] (E:\xampp\htdocs\test\node_modules\sockjs\lib\transport.js:101:22)
    at Timer.listOnTimeout (timers.js:92:15)
 [20:27:35] [nodemon] app crashed - waiting for file changes before starting...
`

**Comment by shahboura** [comment]
Hello, sorry for the late follow-up
what node version are you using?
please refer to the readme file and let me know if you faced any problems
